# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [59]:
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr = arr.reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [60]:
arr1 = np.array([1,1,1,1,1,1,1,1,1,1])
arr1 = arr1.reshape(2,5)

arr2 = np.vstack((arr, arr1))
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [61]:
arr3 = np.hstack((arr, arr1))
arr3

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [62]:
flat = arr.flatten()
flat

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [63]:
high = np.array([[ 0, 1, 2],
                [ 3, 4, 5],
                [ 6, 7, 8],
                [ 9, 10, 11],
                [12, 13, 14]])
high = high.flatten()
high

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [64]:
low = high.reshape(5,3)
low

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [65]:
sqr = np.random.rand(5,5)
sqr = (sqr*50).astype(int)
print(sqr)
sqr = np.round(sqr)
sqr = np.square(sqr)
sqr

[[36 41 25  4 31]
 [47 36 10  3 19]
 [29  1  4  4  3]
 [39 24 15 36  8]
 [11  9 12 23 44]]


array([[1296, 1681,  625,   16,  961],
       [2209, 1296,  100,    9,  361],
       [ 841,    1,   16,   16,    9],
       [1521,  576,  225, 1296,   64],
       [ 121,   81,  144,  529, 1936]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [66]:
mean = np.random.rand(5,6)
mean = (mean*10).astype(int)
print(mean)
mean1 = np.mean(mean)
mean1

[[4 8 9 0 9 0]
 [7 5 1 6 6 5]
 [0 6 2 4 0 7]
 [1 6 0 4 9 6]
 [6 2 1 4 0 4]]


4.066666666666666

## Question:9

### Find the standard deviation of the previous array in Q8?

In [67]:
std = np.std(mean)
std

2.9769484749021475

## Question:10

### Find the median of the previous array in Q8?

In [68]:
med = np.median(mean)
med

4.0

## Question:11

### Find the transpose of the previous array in Q8?

In [69]:
tran = np.transpose(mean)
tran

array([[4, 7, 0, 1, 6],
       [8, 5, 6, 6, 2],
       [9, 1, 2, 0, 1],
       [0, 6, 4, 4, 4],
       [9, 6, 0, 9, 0],
       [0, 5, 7, 6, 4]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [70]:
diag = np.linspace(1,20, 16, dtype=int)
print(diag)
diag = diag.reshape(4,4)
print(diag)
diag_sum = np.trace(diag)
diag_sum

[ 1  2  3  4  6  7  8  9 11 12 13 14 16 17 18 20]
[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 20]]


41

## Question:13

### Find the determinant of the previous array in Q12?

In [71]:
det = np.linalg.det(diag)
det

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [72]:
per5 = np.percentile(diag, 5)
per95 = np.percentile(diag, 95)
print(per5)
per95

1.75


18.5

## Question:15

### How to find if a given array has any null values?

In [73]:
nul = np.linspace(1,10, 16)
print(nul)
nul[2] = np.nan
nul[5] = np.nan
np.argwhere(np.isnan(nul))


[ 1.   1.6  2.2  2.8  3.4  4.   4.6  5.2  5.8  6.4  7.   7.6  8.2  8.8
  9.4 10. ]


array([[2],
       [5]], dtype=int64)